### ISSUE TITLE
Question: how could I access the Tera object with TemplateEngine

### ISSUE THREAD

**Issue by just1602** [Altair-Bueno/axum-template#43]
Hello,

I'm not super experience in rust nor with axum, so maybe there's an easy solution I miss, but I was wondering how I could access the `Tera` object while using axum-template. My goal would be to reload template using `tera.full_reload()` in development and only load them once in production.

**Comment by Altair-Bueno** [comment]
Yes, `Engine` does not offer any way of access to the underlying template renderer. This was a conscious decision to avoid coupling the underlying template engine to the application code. So even though we could add `AsRef`, `AsMut` and `From` implementations for `Engine`, I'm skeptical we should. 

About the usage of `full_reload`, because the function requires mutable access to the tera object, I would suggest you do one of the following options:

1. Rebuild/reload the application on code change: There are tools such as https://crates.io/crates/cargo-watch that automatically rebuilds/reloads the application on file changes, without any kind of code changes.
2. Reload the server when a file is changed: Crates like [notify](https://docs.rs/notify/latest/notify/) would allow you to stop the server, reload whatever you need and start listening again. The advantage would be that your application state wont be lost (ie sessions).
3. Create your own `Engine`: An engine that is able to reload the application if changes are detected. Please note that you would need to add synchronization elements such as [RwLock](https://docs.rs/tokio/latest/tokio/sync/struct.RwLock.html) so you can call the `full_reload` method. Then you could choose one engine or other depending on conditional compilation (https://doc.rust-lang.org/reference/conditional-compilation.html#debug_assertions).

**Comment by just1602** [comment]
Thanks @Altair-Bueno, I'll check cargo watch first, and if it doesn't work, I'll try `notify` or creating a new `Engine`. :)
